name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: echo secret
      env: 
        aaa: ${{ secrets.MY_SECRET }}
      run: echo $aaa
    - name: echo like secret
      run: echo ${{ secrets.MY_SECRET }} | base64
